drop table if exists users;
create table users (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  email varchar,
  username varchar,
  password varchar,
  register_date timestamp NOT NULL DEFAULT current_timestamp
);

drop table if exists articles;

drop table if exists conversations;
create table conversations (
  id int PRIMARY KEY,
  title varchar,
  author varchar,
  body text,
  create_date timestamp NOT NULL DEFAULT current_timestamp
);

